const main = async () => {
  console.log("Hello World");
};

main().catch((err) => {
  console.error(err);
});
